export type { RawValue, Provenance, ValueClassification, RunManifest } from './core/provenance.ts';
export type { FixtureMeta } from './core/fixture.ts';
export { loadFixture } from './core/fixture.ts';
export type { DsOpsConfig } from './config/schema.ts';
export { hashConfig } from './config/schema.ts';
export { DEFAULT_CONFIG } from './config/defaults.ts';
export type { Adapter, SourceRef } from './adapters/types.ts';
export { cssCustomPropsAdapter, extractWith } from './adapters/css-custom-props.ts';
export { toLab, parseColor, looksLikeColor } from './color/convert.ts';
export { ciede2000 } from './color/delta-e.ts';
export { clusterByDeltaE } from './color/cluster.ts';
export type { ColorPoint, Cluster } from './color/cluster.ts';
export { scan } from './commands/scan.ts';
export { sweep } from './commands/sweep.ts';
export type { SweepResult, SweepPoint } from './commands/sweep.ts';
export { audit } from './commands/audit.ts';
export type { AuditReport } from './commands/audit.ts';
export type { Rule, RuleContext, Finding, Severity, RuleTarget } from './rules/types.ts';
export { RULES, rulesForTarget, KNOWN_TARGETS } from './rules/registry.ts';
